name: PHP code quality

on:
  push:
  pull_request:

jobs:
  static:
    name: Static code analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@2.19.1
      with:
        php-version: '8.1'
        tools: composer

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer dependencies
      uses: actions/cache@v3.0.5
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - name: composer install
      run: composer install --no-interaction --no-progress

    - name: Run PHPStan
      run: composer run phpstan

  test:
    name: Tests on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.0', '8.1']

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@2.19.1
      with:
        php-version: ${{ matrix.php }}
        tools: composer
        coverage: xdebug

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer dependencies
      uses: actions/cache@v3.0.5
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - name: composer install
      run: composer install --no-interaction --no-progress

    - name: Run test suite
      run: composer run phpunit

    - uses: codecov/codecov-action@v3.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./build/coverage/clover.xml

    - name: Run PHPInfection
      run: composer run infection
#      env:
#        STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}